name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy Cloudflare Worker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      #
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CF_API_TOKEN: op://automation/cloudflareWorkers/CF_API_TOKEN
          CF_ACCOUNT_ID: op://automation/cloudflareWorkers/CF_ACCOUNT_ID

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          workingDirectory: "./cf-ip"